//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letsencrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("letsencrypt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACME Server: {BaseUri}.
        /// </summary>
        public static string ACMEServerBaseUri {
            get {
                return ResourceManager.GetString("ACMEServerBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding central SSL binding.
        /// </summary>
        public static string AddingcentralSSLbinding {
            get {
                return ResourceManager.GetString("AddingcentralSSLbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding certificate to store.
        /// </summary>
        public static string Addingcertificatetostore {
            get {
                return ResourceManager.GetString("Addingcertificatetostore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding renewal for {target}.
        /// </summary>
        public static string Addingrenewalfortarget {
            get {
                return ResourceManager.GetString("Addingrenewalfortarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding SSL binding.
        /// </summary>
        public static string AddingSSLbinding {
            get {
                return ResourceManager.GetString("AddingSSLbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional files exist in {folderPath} not deleting..
        /// </summary>
        public static string Additionalfilesexistinfolderpath {
            get {
                return ResourceManager.GetString("Additionalfilesexistinfolderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All hosts under all sites need to pass authorization before you can continue..
        /// </summary>
        public static string Allhostsunderallsitesneedtopassauthorizationbeforeyoucancontinue {
            get {
                return ResourceManager.GetString("Allhostsunderallsitesneedtopassauthorizationbeforeyoucancontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer file should now be available at {answerUri}.
        /// </summary>
        public static string AnswerfileshouldnowbeavailableatanswerUri {
            get {
                return ResourceManager.GetString("AnswerfileshouldnowbeavailableatanswerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred: {@e}.
        /// </summary>
        public static string Anunhandledexceptionoccurred {
            get {
                return ResourceManager.GetString("Anunhandledexceptionoccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association of the certificate failed.
        /// </summary>
        public static string Associationofthecertificatefailed {
            get {
                return ResourceManager.GetString("Associationofthecertificatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed: {Status}.
        /// </summary>
        public static string AuthorizationFailedStatus {
            get {
                return ResourceManager.GetString("AuthorizationFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization result: {Status}.
        /// </summary>
        public static string AuthorizationResultStatus {
            get {
                return ResourceManager.GetString("AuthorizationResultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing identifier {dnsIdentifier} using challenge type {CHALLENGE_TYPE_HTTP}.
        /// </summary>
        public static string Authorizingidentifierusingchallengetype {
            get {
                return ResourceManager.GetString("Authorizingidentifierusingchallengetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD login failed.
        /// </summary>
        public static string AzureADloginfailed {
            get {
                return ResourceManager.GetString("AzureADloginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD login successful.
        /// </summary>
        public static string AzureADloginsuccessful {
            get {
                return ResourceManager.GetString("AzureADloginsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Web App.
        /// </summary>
        public static string AzureWebApp {
            get {
                return ResourceManager.GetString("AzureWebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Z: Install a certificate for an Azure Web App..
        /// </summary>
        public static string AzureWebAppMenuOption {
            get {
                return ResourceManager.GetString("AzureWebAppMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the path: {0}.
        /// </summary>
        public static string Cannotfindthepath {
            get {
                return ResourceManager.GetString("Cannotfindthepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralized SSL is only supported on IIS 8 or greater..
        /// </summary>
        public static string CentralizedSSLisonlysupportedonIIS8orgreater {
            get {
                return ResourceManager.GetString("CentralizedSSLisonlysupportedonIIS8orgreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You specified central SSL and there is an existing binding using central SSL with SNI, so there is nothing to update for this binding..
        /// </summary>
        public static string CentralSSLExistingBindingWithSNI {
            get {
                return ResourceManager.GetString("CentralSSLExistingBindingWithSNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate creation failed.  File not found: {pfxFilename}.
        /// </summary>
        public static string CertificatecreationfailedFilenotfound {
            get {
                return ResourceManager.GetString("CertificatecreationfailedFilenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate directory could not be created..
        /// </summary>
        public static string Certificatedirectorycouldnotbecreated {
            get {
                return ResourceManager.GetString("Certificatedirectorycouldnotbecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate folder: {CertOutPath}.
        /// </summary>
        public static string Certificatefolder {
            get {
                return ResourceManager.GetString("Certificatefolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate installation failed.
        /// </summary>
        public static string Certificateinstallationfailed {
            get {
                return ResourceManager.GetString("Certificateinstallationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate store: {CertificateStore}.
        /// </summary>
        public static string Certificatestore {
            get {
                return ResourceManager.GetString("Certificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for renewal of ACME certificates..
        /// </summary>
        public static string CheckforrenewalofACMEcertificates {
            get {
                return ResourceManager.GetString("CheckforrenewalofACMEcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Check in a browser to see if the answer file is being served correctly. If it is, also check the DNSSEC configuration..
        /// </summary>
        public static string Checkinabrowsertoseetheanswerfile {
            get {
                return ResourceManager.GetString("Checkinabrowsertoseetheanswerfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from one of the menu options above: .
        /// </summary>
        public static string Choosefromoneofthemenuoptionsabove {
            get {
                return ResourceManager.GetString("Choosefromoneofthemenuoptionsabove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing certificate store.
        /// </summary>
        public static string Closingcertificatestore {
            get {
                return ResourceManager.GetString("Closingcertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing binding changes to IIS.
        /// </summary>
        public static string CommittingbindingchangestoIIS {
            get {
                return ResourceManager.GetString("CommittingbindingchangestoIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file is incomplete or does not exist..
        /// </summary>
        public static string Configfileisincompleteordoesnotexist {
            get {
                return ResourceManager.GetString("Configfileisincompleteordoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config path: {ConfigPath}.
        /// </summary>
        public static string Configpath {
            get {
                return ResourceManager.GetString("Configpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating registration.
        /// </summary>
        public static string Creatingregistration {
            get {
                return ResourceManager.GetString("Creatingregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating task {taskName} with Windows Task Scheduler at 9am every day..
        /// </summary>
        public static string CreatingtaskNamewithWindowsTaskScheduler {
            get {
                return ResourceManager.GetString("CreatingtaskNamewithWindowsTaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating task to run as current user only when the user is logged on.
        /// </summary>
        public static string Creatingtasktorunascurrentuseronlywhentheuserisloggedon {
            get {
                return ResourceManager.GetString("Creatingtasktorunascurrentuseronlywhentheuserisloggedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Status {StatusDescription}.
        /// </summary>
        public static string DeleteStatusDescription {
            get {
                return ResourceManager.GetString("DeleteStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting answer.
        /// </summary>
        public static string Deletinganswer {
            get {
                return ResourceManager.GetString("Deletinganswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting existing task {taskName} from Windows Task Scheduler..
        /// </summary>
        public static string DeletingexistingtaskNamefromWindowsTaskScheduler {
            get {
                return ResourceManager.GetString("DeletingexistingtaskNamefromWindowsTaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {folderPath}.
        /// </summary>
        public static string Deletingfolderpath {
            get {
                return ResourceManager.GetString("Deletingfolderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting web.config.
        /// </summary>
        public static string Deletingwebconfig {
            get {
                return ResourceManager.GetString("Deletingwebconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree to {0}?.
        /// </summary>
        public static string DoyouagreetoTosLinkUri {
            get {
                return ResourceManager.GetString("DoyouagreetoTosLinkUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to automatically renew this certificate in {0} days? This will add a task scheduler task..
        /// </summary>
        public static string Doyouwanttoautomaticallyrenewthiscertificate {
            get {
                return ResourceManager.GetString("Doyouwanttoautomaticallyrenewthiscertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the certificate into the Certificate Store / Central SSL Store?.
        /// </summary>
        public static string DoyouwanttoinstallthecertificateintotheCertificateStore {
            get {
                return ResourceManager.GetString("DoyouwanttoinstallthecertificateintotheCertificateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace the existing {taskName} task?.
        /// </summary>
        public static string DoyouwanttoreplacetheexistingtaskName {
            get {
                return ResourceManager.GetString("DoyouwanttoreplacetheexistingtaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to specify the user the task will run as?.
        /// </summary>
        public static string Doyouwanttospecifytheuserthetaskwillrunas {
            get {
                return ResourceManager.GetString("Doyouwanttospecifytheuserthetaskwillrunas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add/update the certificate in IIS?.
        /// </summary>
        public static string DoyouwanttoupdatethecertificateinIIS {
            get {
                return ResourceManager.GetString("DoyouwanttoupdatethecertificateinIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all alternative names separated by commas: .
        /// </summary>
        public static string Enterallalternativenamesseparatedbycommas {
            get {
                return ResourceManager.GetString("Enterallalternativenamesseparatedbycommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all site IDs separated by commas: .
        /// </summary>
        public static string EnterallsiteIDsseparatedbycommas {
            get {
                return ResourceManager.GetString("EnterallsiteIDsseparatedbycommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address (not public, used for renewal fail notices): .
        /// </summary>
        public static string Enteranemailaddressnotpublicusedforrenewalfailnotices {
            get {
                return ResourceManager.GetString("Enteranemailaddressnotpublicusedforrenewalfailnotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a site path for WebDAV authentication.
        /// </summary>
        public static string EnterasitepathforWebDAVauthentication {
            get {
                return ResourceManager.GetString("EnterasitepathforWebDAVauthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a host name: .
        /// </summary>
        public static string Enterhostname {
            get {
                return ResourceManager.GetString("Enterhostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a site path (the web root of the host where files will be uploaded for http authentication).
        /// </summary>
        public static string EnterSitePath {
            get {
                return ResourceManager.GetString("EnterSitePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Azure subscription ID.
        /// </summary>
        public static string EntertheAzuresubscriptionID {
            get {
                return ResourceManager.GetString("EntertheAzuresubscriptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Azure web app ID.
        /// </summary>
        public static string EntertheAzurewebappID {
            get {
                return ResourceManager.GetString("EntertheAzurewebappID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the FTP password: .
        /// </summary>
        public static string EntertheFTPpassword {
            get {
                return ResourceManager.GetString("EntertheFTPpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the FTP username: .
        /// </summary>
        public static string EntertheFTPusername {
            get {
                return ResourceManager.GetString("EntertheFTPusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the site host name: .
        /// </summary>
        public static string Enterthesitehostname {
            get {
                return ResourceManager.GetString("Enterthesitehostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username (Domain\\username): .
        /// </summary>
        public static string Entertheusername {
            get {
                return ResourceManager.GetString("Entertheusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user&apos;s password: .
        /// </summary>
        public static string Entertheuserspassword {
            get {
                return ResourceManager.GetString("Entertheuserspassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the WebDAV password: .
        /// </summary>
        public static string EntertheWebDAVpassword {
            get {
                return ResourceManager.GetString("EntertheWebDAVpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the WebDAV username: .
        /// </summary>
        public static string EntertheWebDAVusername {
            get {
                return ResourceManager.GetString("EntertheWebDAVusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating FTP directory {@ex}.
        /// </summary>
        public static string ErrorcreatingFTPdirectory {
            get {
                return ResourceManager.GetString("ErrorcreatingFTPdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the certificate directory, {CertOutPath}. {@ex}.
        /// </summary>
        public static string Errorcreatingthecertificatedirectory {
            get {
                return ResourceManager.GetString("Errorcreatingthecertificatedirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file/folder {@ex}.
        /// </summary>
        public static string Errordeletingfileorfolder {
            get {
                return ResourceManager.GetString("Errordeletingfileorfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered while opening certificate store. Error: {@ex}.
        /// </summary>
        public static string Errorencounteredwhileopeningcertificatestore {
            get {
                return ResourceManager.GetString("Errorencounteredwhileopeningcertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting archive {@ex}.
        /// </summary>
        public static string Errorexportingarchive {
            get {
                return ResourceManager.GetString("Errorexportingarchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting folder structure. Error: {@ex}.
        /// </summary>
        public static string Erroroccuredwhiledeletingfolderstructure {
            get {
                return ResourceManager.GetString("Erroroccuredwhiledeletingfolderstructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the IIS version.
        /// </summary>
        public static string ErrorreadingtheIISversion {
            get {
                return ResourceManager.GetString("ErrorreadingtheIISversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing certificate {@ex}.
        /// </summary>
        public static string Errorremovingcertificate {
            get {
                return ResourceManager.GetString("Errorremovingcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving certificate {@ex}.
        /// </summary>
        public static string Errorsavingcertificate {
            get {
                return ResourceManager.GetString("Errorsavingcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting binding {@ex}.
        /// </summary>
        public static string Errorsettingbinding {
            get {
                return ResourceManager.GetString("Errorsettingbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error warming up site: {@ex}.
        /// </summary>
        public static string Errorwarmingupsite {
            get {
                return ResourceManager.GetString("Errorwarmingupsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse commandline.
        /// </summary>
        public static string Failedtoparsecommandline {
            get {
                return ResourceManager.GetString("Failedtoparsecommandline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        public static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  F: Generate a certificate via FTP/FTPS and install it manually..
        /// </summary>
        public static string FTPMenuOption {
            get {
                return ResourceManager.GetString("FTPMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full error details {@authzState}.
        /// </summary>
        public static string FullErrorDetailsauthzState {
            get {
                return ResourceManager.GetString("FullErrorDetailsauthzState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  A: Get certificates for all hosts.
        /// </summary>
        public static string GetcertificatesforallhostsMenu {
            get {
                return ResourceManager.GetString("GetcertificatesforallhostsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ACME server directory.
        /// </summary>
        public static string GettingACMEserverdirectory {
            get {
                return ResourceManager.GetString("GettingACMEserverdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host: {0}.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS Binding not created due to HTTP binding having specific IP; Manually create the HTTPS binding and retry.
        /// </summary>
        public static string HTTPSbindingnotcreatedduetoHTTPbindinghavingspecificIP {
            get {
                return ResourceManager.GetString("HTTPSbindingnotcreatedduetoHTTPbindinghavingspecificIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS.
        /// </summary>
        public static string IIS {
            get {
                return ResourceManager.GetString("IIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize failed: This could be caused by IIS not being setup to handle extensionless static files.Here&apos;s how to fix that:
        ///  1.In IIS manager goto Site/ Server-&gt;Handler Mappings-&gt;View Ordered List
        ///  2.Move the StaticFile mapping above the ExtensionlessUrlHandler mappings. (like this http://i.stack.imgur.com/nkvrL.png)
        ///  3.If you need to make changes to your web.config file, update the one at Web_Config.xml.
        /// </summary>
        public static string IISAuthorizeFailedMessage {
            get {
                return ResourceManager.GetString("IISAuthorizeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS will serve the new certificate after the application pool idle timeout has expired or the app pool is recycled..
        /// </summary>
        public static string IISCertificateTakesEffectAfterAppPoolRecycle {
            get {
                return ResourceManager.GetString("IISCertificateTakesEffectAfterAppPoolRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  I: Install certificates for the local IIS.
        /// </summary>
        public static string IISMenuOption {
            get {
                return ResourceManager.GetString("IISMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Site Server.
        /// </summary>
        public static string IISSiteServer {
            get {
                return ResourceManager.GetString("IISSiteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  S: Generate a single San certificate for multiple sites..
        /// </summary>
        public static string IISSiteServerMenuOption {
            get {
                return ResourceManager.GetString("IISSiteServerMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  S: for all sites on the server.
        /// </summary>
        public static string IISSiteServerMenuOption2 {
            get {
                return ResourceManager.GetString("IISSiteServerMenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Version not found in windows registry. Skipping scan..
        /// </summary>
        public static string IISVersionnotfoundinwindowsregistry {
            get {
                return ResourceManager.GetString("IISVersionnotfoundinwindowsregistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the certificate failed.
        /// </summary>
        public static string Installationofthecertificatefailed {
            get {
                return ResourceManager.GetString("Installationofthecertificatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing central SSL certificate.
        /// </summary>
        public static string InstallingcentralSSLcertificate {
            get {
                return ResourceManager.GetString("InstallingcentralSSLcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SSL certificate in IIS.
        /// </summary>
        public static string InstallingSSLcertificateinIIS {
            get {
                return ResourceManager.GetString("InstallingSSLcertificateinIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SSL certificate in the certificate store.
        /// </summary>
        public static string InstallingSSLcertificateinthecertificatestore {
            get {
                return ResourceManager.GetString("InstallingSSLcertificateinthecertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line options.
        /// </summary>
        public static string Invalidcommandlineoptions {
            get {
                return ResourceManager.GetString("Invalidcommandlineoptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading registration from {registrationPath}.
        /// </summary>
        public static string LoadingregistrationfromregistrationPath {
            get {
                return ResourceManager.GetString("LoadingregistrationfromregistrationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Signer from {signerPath}.
        /// </summary>
        public static string LoadingSignerfromsignerPath {
            get {
                return ResourceManager.GetString("LoadingSignerfromsignerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  M: Generate a certificate manually..
        /// </summary>
        public static string ManualMenuOption {
            get {
                return ResourceManager.GetString("ManualMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name} has too many hosts for a San certificate. Let&apos;s Encrypt currently has a maximum of 100 alternative names per certificate..
        /// </summary>
        public static string NamehastoomanyhostsforaSancertificate {
            get {
                return ResourceManager.GetString("NamehastoomanyhostsforaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTTP binding for {host} on {name}.
        /// </summary>
        public static string NoHTTPbindingforhostonsitename {
            get {
                return ResourceManager.GetString("NoHTTPbindingforhostonsitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IIS bindings with host names were found. Please add one using IIS Manager. A host name and site path are required to verify domain ownership..
        /// </summary>
        public static string NoIISbindingswithhostnameswerefound {
            get {
                return ResourceManager.GetString("NoIISbindingswithhostnameswerefound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin supplied.
        /// </summary>
        public static string Nopluginsupplied {
            get {
                return ResourceManager.GetString("Nopluginsupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened certificate store {Name}.
        /// </summary>
        public static string Openedcertificatestore {
            get {
                return ResourceManager.GetString("Openedcertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherwise, manually create the HTTPS binding and rerun the application..
        /// </summary>
        public static string OtherwisemanuallycreatetheHTTPSbinding {
            get {
                return ResourceManager.GetString("OtherwisemanuallycreatetheHTTPSbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Y to continue. Press any other key to stop installing the certificate: .
        /// </summary>
        public static string PressYtocontinueoranyotherkeytostopinstalling {
            get {
                return ResourceManager.GetString("PressYtocontinueoranyotherkeytostopinstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (y/n).
        /// </summary>
        public static string PromptYesNo {
            get {
                return ResourceManager.GetString("PromptYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxying via {0}.
        /// </summary>
        public static string Proxyingvia {
            get {
                return ResourceManager.GetString("Proxyingvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Q: Quit.
        /// </summary>
        public static string QuitMenu {
            get {
                return ResourceManager.GetString("QuitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing authorization.
        /// </summary>
        public static string Refreshingauthorization {
            get {
                return ResourceManager.GetString("Refreshingauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing certificate from store {@cert}.
        /// </summary>
        public static string Removingcertificatefromstore {
            get {
                return ResourceManager.GetString("Removingcertificatefromstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing existing scheduled renewal {existing}.
        /// </summary>
        public static string Removingexistingscheduledrenewal {
            get {
                return ResourceManager.GetString("Removingexistingscheduledrenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew after.
        /// </summary>
        public static string Renewafter {
            get {
                return ResourceManager.GetString("Renewafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal period: {RenewalPeriod}.
        /// </summary>
        public static string Renewalperiod {
            get {
                return ResourceManager.GetString("Renewalperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal scheduled {result}.
        /// </summary>
        public static string Renewalscheduledresult {
            get {
                return ResourceManager.GetString("Renewalscheduledresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed: status = {0}.
        /// </summary>
        public static string RequestFailedStatusCode {
            get {
                return ResourceManager.GetString("RequestFailedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting certificate.
        /// </summary>
        public static string Requestingcertificate {
            get {
                return ResourceManager.GetString("Requestingcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status: {StatusCode}.
        /// </summary>
        public static string RequestStatusCode {
            get {
                return ResourceManager.GetString("RequestStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Key Bits less than 1024 is not secure. Letting ACMESharp default key bits. http://openssl.org/docs/manmaster/crypto/RSA_generate_key_ex.html.
        /// </summary>
        public static string RSAKeyBitslessthan1024Warning {
            get {
                return ResourceManager.GetString("RSAKeyBitslessthan1024Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {Script}.
        /// </summary>
        public static string RunningScript {
            get {
                return ResourceManager.GetString("RunningScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {Script} with {parameters}.
        /// </summary>
        public static string RunningScriptwithparameters {
            get {
                return ResourceManager.GetString("RunningScriptwithparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the application with --san to generate a San certificate.
        /// </summary>
        public static string RuntheapplicationwithsantogenerateaSancertificate {
            get {
                return ResourceManager.GetString("RuntheapplicationwithsantogenerateaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Certificates are not supported by the Azure Web App Plugin..
        /// </summary>
        public static string SanCertificatesarenotsupportedbytheAzureWebAppPlugin {
            get {
                return ResourceManager.GetString("SanCertificatesarenotsupportedbytheAzureWebAppPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Option Enabled: Running per site and not per host.
        /// </summary>
        public static string SanOptionEnabled {
            get {
                return ResourceManager.GetString("SanOptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving certificate to {file}.
        /// </summary>
        public static string Savingcertificatetofile {
            get {
                return ResourceManager.GetString("Savingcertificatetofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving issuer certificate to {file}.
        /// </summary>
        public static string Savingissuercertificatetofile {
            get {
                return ResourceManager.GetString("Savingissuercertificatetofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving registration.
        /// </summary>
        public static string Savingregistration {
            get {
                return ResourceManager.GetString("Savingregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving signer.
        /// </summary>
        public static string Savingsigner {
            get {
                return ResourceManager.GetString("Savingsigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning IIS site bindings for hosts.
        /// </summary>
        public static string ScanningIISsitebindingsforhosts {
            get {
                return ResourceManager.GetString("ScanningIISsitebindingsforhosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning IIS sites.
        /// </summary>
        public static string ScanningIISsites {
            get {
                return ResourceManager.GetString("ScanningIISsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See {0} for more information..
        /// </summary>
        public static string Seelinkformoreinformation {
            get {
                return ResourceManager.GetString("Seelinkformoreinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the host names for the certificate
        ///You can enter multiple IDs comma-separated e.g. 1,2,3.
        /// </summary>
        public static string Selectthehostnamesforthecertificate {
            get {
                return ResourceManager.GetString("Selectthehostnamesforthecertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set private key exportable.
        /// </summary>
        public static string Setprivatekeyexportable {
            get {
                return ResourceManager.GetString("Setprivatekeyexportable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Binding failed.
        /// </summary>
        public static string SSLBindingfailed {
            get {
                return ResourceManager.GetString("SSLBindingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting answer.
        /// </summary>
        public static string Submittinganswer {
            get {
                return ResourceManager.GetString("Submittinganswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ACME server was probably unable to reach {answerUri}.
        /// </summary>
        public static string TheACMEserverwasprobablyunabletoreachanswerUri {
            get {
                return ResourceManager.GetString("TheACMEserverwasprobablyunabletoreachanswerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FTP Credentials are not set. Please specify them and try again..
        /// </summary>
        public static string TheFTPCredentialsarenotset {
            get {
                return ResourceManager.GetString("TheFTPCredentialsarenotset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP binding is IP specific; the app can create it. However, if you have other HTTPS sites they will all get an invalid certificate error until you manually edit one of their HTTPS bindings..
        /// </summary>
        public static string TheHTTPbindingisIPspecific {
            get {
                return ResourceManager.GetString("TheHTTPbindingisIPspecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebDAV credentials are not set. Please specify them and try again..
        /// </summary>
        public static string TheWebDAVcredentialsarenotset {
            get {
                return ResourceManager.GetString("TheWebDAVcredentialsarenotset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program must be run from an administrative command prompt..
        /// </summary>
        public static string Thisprogrammustberunfromanadministrativecommandprompt {
            get {
                return ResourceManager.GetString("Thisprogrammustberunfromanadministrativecommandprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find IIS site ID #{0}.
        /// </summary>
        public static string UnabletofindIISsiteID {
            get {
                return ResourceManager.GetString("UnabletofindIISsiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set RSA Key Bits, Letting ACMESharp default key bits, Error: {@ex}.
        /// </summary>
        public static string UnabletosetRSAKeyBits {
            get {
                return ResourceManager.GetString("UnabletosetRSAKeyBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating existing SSL binding.
        /// </summary>
        public static string UpdatingexistingSSLbinding {
            get {
                return ResourceManager.GetString("UpdatingexistingSSLbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating registration.
        /// </summary>
        public static string Updatingregistration {
            get {
                return ResourceManager.GetString("Updatingregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Status {StatusDescription}.
        /// </summary>
        public static string UploadStatusDescription {
            get {
                return ResourceManager.GetString("UploadStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using centralized SSL path: {CentralSslStore}.
        /// </summary>
        public static string UsingcentralizedSSLpath {
            get {
                return ResourceManager.GetString("UsingcentralizedSSLpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using SSL.
        /// </summary>
        public static string UsingSSL {
            get {
                return ResourceManager.GetString("UsingSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for site to warm up....
        /// </summary>
        public static string Waitingforsitetowarmup {
            get {
                return ResourceManager.GetString("Waitingforsitetowarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning creating SSL binding for {0}..
        /// </summary>
        public static string WarningcreatingSSLbindingforhost {
            get {
                return ResourceManager.GetString("WarningcreatingSSLbindingforhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebDAV.
        /// </summary>
        public static string WebDAV {
            get {
                return ResourceManager.GetString("WebDAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  W: Generate a certificate via WebDAV and install it manually..
        /// </summary>
        public static string WebDAVMenuOption {
            get {
                return ResourceManager.GetString("WebDAVMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing challenge answer to {answerPath}.
        /// </summary>
        public static string WritingchallengeanswertoanswerPath {
            get {
                return ResourceManager.GetString("WritingchallengeanswertoanswerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing web.config to add extensionless mime type to {webConfigPath}.
        /// </summary>
        public static string WritingWebConfig {
            get {
                return ResourceManager.GetString("WritingWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find the certificate at {pfxFilename}.
        /// </summary>
        public static string YoucanfindthecertificateatpfxFilename {
            get {
                return ResourceManager.GetString("YoucanfindthecertificateatpfxFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered too many hosts for a San certificate. Let&apos;s Encrypt currently has a maximum of 100 alternative names per certificate..
        /// </summary>
        public static string YouenteredtoomanyhostsforaSancertificate {
            get {
                return ResourceManager.GetString("YouenteredtoomanyhostsforaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too many hosts for a San certificate. Let&apos;s Encrypt currently has a maximum of 100 alternative names per certificate..
        /// </summary>
        public static string YouhavetoomanyhostsforaSancertificate {
            get {
                return ResourceManager.GetString("YouhavetoomanyhostsforaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to edit the binding, turn off SNI, click OK, edit it again, enable SNI and click OK. That should fix the error..
        /// </summary>
        public static string YouneedtoeditthebindingturnoffSNI {
            get {
                return ResourceManager.GetString("YouneedtoeditthebindingturnoffSNI", resourceCulture);
            }
        }
    }
}
