//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class publishData {
    
    private publishDataPublishProfile[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("publishProfile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public publishDataPublishProfile[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class publishDataPublishProfile {
    
    private publishDataPublishProfileDatabasesAdd[] databasesField;
    
    private string profileNameField;
    
    private string publishMethodField;
    
    private string publishUrlField;
    
    private string msdeploySiteField;
    
    private string userNameField;
    
    private string userPWDField;
    
    private string destinationAppUrlField;
    
    private string sQLServerDBConnectionStringField;
    
    private string mySQLDBConnectionStringField;
    
    private string hostingProviderForumLinkField;
    
    private string controlPanelLinkField;
    
    private string webSystemField;
    
    private string ftpPassiveModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("add", typeof(publishDataPublishProfileDatabasesAdd), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public publishDataPublishProfileDatabasesAdd[] databases {
        get {
            return this.databasesField;
        }
        set {
            this.databasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string profileName {
        get {
            return this.profileNameField;
        }
        set {
            this.profileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string publishMethod {
        get {
            return this.publishMethodField;
        }
        set {
            this.publishMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string publishUrl {
        get {
            return this.publishUrlField;
        }
        set {
            this.publishUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string msdeploySite {
        get {
            return this.msdeploySiteField;
        }
        set {
            this.msdeploySiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userPWD {
        get {
            return this.userPWDField;
        }
        set {
            this.userPWDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destinationAppUrl {
        get {
            return this.destinationAppUrlField;
        }
        set {
            this.destinationAppUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SQLServerDBConnectionString {
        get {
            return this.sQLServerDBConnectionStringField;
        }
        set {
            this.sQLServerDBConnectionStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mySQLDBConnectionString {
        get {
            return this.mySQLDBConnectionStringField;
        }
        set {
            this.mySQLDBConnectionStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostingProviderForumLink {
        get {
            return this.hostingProviderForumLinkField;
        }
        set {
            this.hostingProviderForumLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controlPanelLink {
        get {
            return this.controlPanelLinkField;
        }
        set {
            this.controlPanelLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string webSystem {
        get {
            return this.webSystemField;
        }
        set {
            this.webSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ftpPassiveMode {
        get {
            return this.ftpPassiveModeField;
        }
        set {
            this.ftpPassiveModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class publishDataPublishProfileDatabasesAdd {
    
    private string nameField;
    
    private string connectionStringField;
    
    private string providerNameField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string connectionString {
        get {
            return this.connectionStringField;
        }
        set {
            this.connectionStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string providerName {
        get {
            return this.providerNameField;
        }
        set {
            this.providerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
