//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsEncrypt.ACME.Simple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LetsEncrypt.ACME.Simple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding central SSL binding.
        /// </summary>
        internal static string AddingcentralSSLbinding {
            get {
                return ResourceManager.GetString("AddingcentralSSLbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding certificate to store.
        /// </summary>
        internal static string Addingcertificatetostore {
            get {
                return ResourceManager.GetString("Addingcertificatetostore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding SSL binding.
        /// </summary>
        internal static string AddingSSLbinding {
            get {
                return ResourceManager.GetString("AddingSSLbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional files exist in {folderPath} not deleting..
        /// </summary>
        internal static string Additionalfilesexistinfolderpath {
            get {
                return ResourceManager.GetString("Additionalfilesexistinfolderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All hosts under all sites need to pass authorization before you can continue..
        /// </summary>
        internal static string Allhostsunderallsitesneedtopassauthorizationbeforeyoucancontinue {
            get {
                return ResourceManager.GetString("Allhostsunderallsitesneedtopassauthorizationbeforeyoucancontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer file should now be available at {answerUri}.
        /// </summary>
        internal static string AnswerfileshouldnowbeavailableatanswerUri {
            get {
                return ResourceManager.GetString("AnswerfileshouldnowbeavailableatanswerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred: {@e}.
        /// </summary>
        internal static string Anunhandledexceptionoccurred {
            get {
                return ResourceManager.GetString("Anunhandledexceptionoccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association of the certificate failed.
        /// </summary>
        internal static string Associationofthecertificatefailed {
            get {
                return ResourceManager.GetString("Associationofthecertificatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed: {Status}.
        /// </summary>
        internal static string AuthorizationFailedStatus {
            get {
                return ResourceManager.GetString("AuthorizationFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization result: {Status}.
        /// </summary>
        internal static string AuthorizationResultStatus {
            get {
                return ResourceManager.GetString("AuthorizationResultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing identifier {dnsIdentifier} using challenge type {CHALLENGE_TYPE_HTTP}.
        /// </summary>
        internal static string Authorizingidentifierusingchallengetype {
            get {
                return ResourceManager.GetString("Authorizingidentifierusingchallengetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD login failed.
        /// </summary>
        internal static string AzureADloginfailed {
            get {
                return ResourceManager.GetString("AzureADloginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD login successful.
        /// </summary>
        internal static string AzureADloginsuccessful {
            get {
                return ResourceManager.GetString("AzureADloginsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Web App.
        /// </summary>
        internal static string AzureWebApp {
            get {
                return ResourceManager.GetString("AzureWebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Z: Install a certificate for an Azure Web App..
        /// </summary>
        internal static string AzureWebAppMenuOption {
            get {
                return ResourceManager.GetString("AzureWebAppMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the path: {0}.
        /// </summary>
        internal static string Cannotfindthepath {
            get {
                return ResourceManager.GetString("Cannotfindthepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralized SSL is only supported on IIS 8 or greater..
        /// </summary>
        internal static string CentralizedSSLisonlysupportedonIIS8orgreater {
            get {
                return ResourceManager.GetString("CentralizedSSLisonlysupportedonIIS8orgreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You specified central SSL and there is an existing binding using central SSL with SNI, so there is nothing to update for this binding..
        /// </summary>
        internal static string CentralSSLExistingBindingWithSNI {
            get {
                return ResourceManager.GetString("CentralSSLExistingBindingWithSNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate installation failed.
        /// </summary>
        internal static string Certificateinstallationfailed {
            get {
                return ResourceManager.GetString("Certificateinstallationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Check in a browser to see if the answer file is being served correctly. If it is, also check the DNSSEC configuration..
        /// </summary>
        internal static string Checkinabrowsertoseetheanswerfile {
            get {
                return ResourceManager.GetString("Checkinabrowsertoseetheanswerfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from one of the menu options above: .
        /// </summary>
        internal static string Choosefromoneofthemenuoptionsabove {
            get {
                return ResourceManager.GetString("Choosefromoneofthemenuoptionsabove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing certificate store.
        /// </summary>
        internal static string Closingcertificatestore {
            get {
                return ResourceManager.GetString("Closingcertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing binding changes to IIS.
        /// </summary>
        internal static string CommittingbindingchangestoIIS {
            get {
                return ResourceManager.GetString("CommittingbindingchangestoIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file is incomplete or does not exist..
        /// </summary>
        internal static string Configfileisincompleteordoesnotexist {
            get {
                return ResourceManager.GetString("Configfileisincompleteordoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating registration.
        /// </summary>
        internal static string Creatingregistration {
            get {
                return ResourceManager.GetString("Creatingregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Status {StatusDescription}.
        /// </summary>
        internal static string DeleteStatusDescription {
            get {
                return ResourceManager.GetString("DeleteStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting answer.
        /// </summary>
        internal static string Deletinganswer {
            get {
                return ResourceManager.GetString("Deletinganswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {folderPath}.
        /// </summary>
        internal static string Deletingfolderpath {
            get {
                return ResourceManager.GetString("Deletingfolderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting web.config.
        /// </summary>
        internal static string Deletingwebconfig {
            get {
                return ResourceManager.GetString("Deletingwebconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree to {0}?.
        /// </summary>
        internal static string DoyouagreetoTosLinkUri {
            get {
                return ResourceManager.GetString("DoyouagreetoTosLinkUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to automatically renew this certificate in {0} days? This will add a task scheduler task..
        /// </summary>
        internal static string Doyouwanttoautomaticallyrenewthiscertificate {
            get {
                return ResourceManager.GetString("Doyouwanttoautomaticallyrenewthiscertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the certificate into the Certificate Store / Central SSL Store?.
        /// </summary>
        internal static string DoyouwanttoinstallthecertificateintotheCertificateStore {
            get {
                return ResourceManager.GetString("DoyouwanttoinstallthecertificateintotheCertificateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add/update the certificate in IIS?.
        /// </summary>
        internal static string DoyouwanttoupdatethecertificateinIIS {
            get {
                return ResourceManager.GetString("DoyouwanttoupdatethecertificateinIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all site IDs separated by commas.
        /// </summary>
        internal static string EnterallsiteIDsseparatedbycommas {
            get {
                return ResourceManager.GetString("EnterallsiteIDsseparatedbycommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address (not public, used for renewal fail notices): .
        /// </summary>
        internal static string Enteranemailaddressnotpublicusedforrenewalfailnotices {
            get {
                return ResourceManager.GetString("Enteranemailaddressnotpublicusedforrenewalfailnotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a site path for WebDAV authentication.
        /// </summary>
        internal static string EnterasitepathforWebDAVauthentication {
            get {
                return ResourceManager.GetString("EnterasitepathforWebDAVauthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a host name: .
        /// </summary>
        internal static string Enterhostname {
            get {
                return ResourceManager.GetString("Enterhostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a site path (the web root of the host where files will be uploaded for http authentication).
        /// </summary>
        internal static string EnterSitePath {
            get {
                return ResourceManager.GetString("EnterSitePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Azure subscription ID.
        /// </summary>
        internal static string EntertheAzuresubscriptionID {
            get {
                return ResourceManager.GetString("EntertheAzuresubscriptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Azure web app ID.
        /// </summary>
        internal static string EntertheAzurewebappID {
            get {
                return ResourceManager.GetString("EntertheAzurewebappID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the FTP password: .
        /// </summary>
        internal static string EntertheFTPpassword {
            get {
                return ResourceManager.GetString("EntertheFTPpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the FTP username: .
        /// </summary>
        internal static string EntertheFTPusername {
            get {
                return ResourceManager.GetString("EntertheFTPusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the site host name: .
        /// </summary>
        internal static string Enterthesitehostname {
            get {
                return ResourceManager.GetString("Enterthesitehostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the WebDAV password: .
        /// </summary>
        internal static string EntertheWebDAVpassword {
            get {
                return ResourceManager.GetString("EntertheWebDAVpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the WebDAV username: .
        /// </summary>
        internal static string EntertheWebDAVusername {
            get {
                return ResourceManager.GetString("EntertheWebDAVusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating FTP directory {@ex}.
        /// </summary>
        internal static string ErrorcreatingFTPdirectory {
            get {
                return ResourceManager.GetString("ErrorcreatingFTPdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file/folder {@ex}.
        /// </summary>
        internal static string Errordeletingfileorfolder {
            get {
                return ResourceManager.GetString("Errordeletingfileorfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered while opening certificate store. Error: {@ex}.
        /// </summary>
        internal static string Errorencounteredwhileopeningcertificatestore {
            get {
                return ResourceManager.GetString("Errorencounteredwhileopeningcertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting archive {@ex}.
        /// </summary>
        internal static string Errorexportingarchive {
            get {
                return ResourceManager.GetString("Errorexportingarchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting folder structure. Error: {@ex}.
        /// </summary>
        internal static string Erroroccuredwhiledeletingfolderstructure {
            get {
                return ResourceManager.GetString("Erroroccuredwhiledeletingfolderstructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the IIS version.
        /// </summary>
        internal static string ErrorreadingtheIISversion {
            get {
                return ResourceManager.GetString("ErrorreadingtheIISversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing certificate {@ex}.
        /// </summary>
        internal static string Errorremovingcertificate {
            get {
                return ResourceManager.GetString("Errorremovingcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving certificate {@ex}.
        /// </summary>
        internal static string Errorsavingcertificate {
            get {
                return ResourceManager.GetString("Errorsavingcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting binding {@ex}.
        /// </summary>
        internal static string Errorsettingbinding {
            get {
                return ResourceManager.GetString("Errorsettingbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error warming up site: {@ex}.
        /// </summary>
        internal static string Errorwarmingupsite {
            get {
                return ResourceManager.GetString("Errorwarmingupsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        internal static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  F: Generate a certificate via FTP/FTPS and install it manually..
        /// </summary>
        internal static string FTPMenuOption {
            get {
                return ResourceManager.GetString("FTPMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full error details {@authzState}.
        /// </summary>
        internal static string FullErrorDetailsauthzState {
            get {
                return ResourceManager.GetString("FullErrorDetailsauthzState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  A: Get certificates for all hosts.
        /// </summary>
        internal static string GetcertificatesforallhostsMenu {
            get {
                return ResourceManager.GetString("GetcertificatesforallhostsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ACME server directory.
        /// </summary>
        internal static string GettingACMEserverdirectory {
            get {
                return ResourceManager.GetString("GettingACMEserverdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host: {0}.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS Binding not created due to HTTP binding having specific IP; Manually create the HTTPS binding and retry.
        /// </summary>
        internal static string HTTPSbindingnotcreatedduetoHTTPbindinghavingspecificIP {
            get {
                return ResourceManager.GetString("HTTPSbindingnotcreatedduetoHTTPbindinghavingspecificIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS.
        /// </summary>
        internal static string IIS {
            get {
                return ResourceManager.GetString("IIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize failed: This could be caused by IIS not being setup to handle extensionless static files.Here&apos;s how to fix that:
        ///  1.In IIS manager goto Site/ Server-&gt;Handler Mappings-&gt;View Ordered List
        ///  2.Move the StaticFile mapping above the ExtensionlessUrlHandler mappings. (like this http://i.stack.imgur.com/nkvrL.png)
        ///  3.If you need to make changes to your web.config file, update the one at Web_Config.xml.
        /// </summary>
        internal static string IISAuthorizeFailedMessage {
            get {
                return ResourceManager.GetString("IISAuthorizeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS will serve the new certificate after the application pool idle timeout has expired or the app pool is recycled..
        /// </summary>
        internal static string IISCertificateTakesEffectAfterAppPoolRecycle {
            get {
                return ResourceManager.GetString("IISCertificateTakesEffectAfterAppPoolRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  I: Install certificates for the local IIS.
        /// </summary>
        internal static string IISMenuOption {
            get {
                return ResourceManager.GetString("IISMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Site Server.
        /// </summary>
        internal static string IISSiteServer {
            get {
                return ResourceManager.GetString("IISSiteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S: Generate a single San certificate for multiple sites..
        /// </summary>
        internal static string IISSiteServerMenuOption {
            get {
                return ResourceManager.GetString("IISSiteServerMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  S: for all sites on the server.
        /// </summary>
        internal static string IISSiteServerMenuOption2 {
            get {
                return ResourceManager.GetString("IISSiteServerMenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Version not found in windows registry. Skipping scan..
        /// </summary>
        internal static string IISVersionnotfoundinwindowsregistry {
            get {
                return ResourceManager.GetString("IISVersionnotfoundinwindowsregistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the certificate failed.
        /// </summary>
        internal static string Installationofthecertificatefailed {
            get {
                return ResourceManager.GetString("Installationofthecertificatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing central SSL certificate.
        /// </summary>
        internal static string InstallingcentralSSLcertificate {
            get {
                return ResourceManager.GetString("InstallingcentralSSLcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SSL certificate in IIS.
        /// </summary>
        internal static string InstallingSSLcertificateinIIS {
            get {
                return ResourceManager.GetString("InstallingSSLcertificateinIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SSL certificate in the certificate store.
        /// </summary>
        internal static string InstallingSSLcertificateinthecertificatestore {
            get {
                return ResourceManager.GetString("InstallingSSLcertificateinthecertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading registration from {registrationPath}.
        /// </summary>
        internal static string LoadingregistrationfromregistrationPath {
            get {
                return ResourceManager.GetString("LoadingregistrationfromregistrationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Signer from {signerPath}.
        /// </summary>
        internal static string LoadingSignerfromsignerPath {
            get {
                return ResourceManager.GetString("LoadingSignerfromsignerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  M: Generate a certificate manually..
        /// </summary>
        internal static string ManualMenuOption {
            get {
                return ResourceManager.GetString("ManualMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name} has too many hosts for a San certificate. Let&apos;s Encrypt currently has a maximum of 100 alternative names per certificate..
        /// </summary>
        internal static string NamehastoomanyhostsforaSancertificate {
            get {
                return ResourceManager.GetString("NamehastoomanyhostsforaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTTP binding for {host} on {name}.
        /// </summary>
        internal static string NoHTTPbindingforhostonsitename {
            get {
                return ResourceManager.GetString("NoHTTPbindingforhostonsitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IIS bindings with host names were found. Please add one using IIS Manager. A host name and site path are required to verify domain ownership..
        /// </summary>
        internal static string NoIISbindingswithhostnameswerefound {
            get {
                return ResourceManager.GetString("NoIISbindingswithhostnameswerefound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened certificate store {Name}.
        /// </summary>
        internal static string Openedcertificatestore {
            get {
                return ResourceManager.GetString("Openedcertificatestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherwise, manually create the HTTPS binding and rerun the application..
        /// </summary>
        internal static string OtherwisemanuallycreatetheHTTPSbinding {
            get {
                return ResourceManager.GetString("OtherwisemanuallycreatetheHTTPSbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Y to continue. Press any other key to stop installing the certificate: .
        /// </summary>
        internal static string PressYtocontinueoranyotherkeytostopinstalling {
            get {
                return ResourceManager.GetString("PressYtocontinueoranyotherkeytostopinstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxying via {0}.
        /// </summary>
        internal static string Proxyingvia {
            get {
                return ResourceManager.GetString("Proxyingvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Q: Quit.
        /// </summary>
        internal static string QuitMenu {
            get {
                return ResourceManager.GetString("QuitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing authorization.
        /// </summary>
        internal static string Refreshingauthorization {
            get {
                return ResourceManager.GetString("Refreshingauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing certificate from store {@cert}.
        /// </summary>
        internal static string Removingcertificatefromstore {
            get {
                return ResourceManager.GetString("Removingcertificatefromstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew after.
        /// </summary>
        internal static string Renewafter {
            get {
                return ResourceManager.GetString("Renewafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed: status = {0}.
        /// </summary>
        internal static string RequestFailedStatusCode {
            get {
                return ResourceManager.GetString("RequestFailedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting certificate.
        /// </summary>
        internal static string Requestingcertificate {
            get {
                return ResourceManager.GetString("Requestingcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status: {StatusCode}.
        /// </summary>
        internal static string RequestStatusCode {
            get {
                return ResourceManager.GetString("RequestStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Key Bits less than 1024 is not secure. Letting ACMESharp default key bits. http://openssl.org/docs/manmaster/crypto/RSA_generate_key_ex.html.
        /// </summary>
        internal static string RSAKeyBitslessthan1024Warning {
            get {
                return ResourceManager.GetString("RSAKeyBitslessthan1024Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {Script}.
        /// </summary>
        internal static string RunningScript {
            get {
                return ResourceManager.GetString("RunningScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {Script} with {parameters}.
        /// </summary>
        internal static string RunningScriptwithparameters {
            get {
                return ResourceManager.GetString("RunningScriptwithparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the application with --san to generate a San certificate.
        /// </summary>
        internal static string RuntheapplicationwithsantogenerateaSancertificate {
            get {
                return ResourceManager.GetString("RuntheapplicationwithsantogenerateaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Certificates are not supported by the Azure Web App Plugin..
        /// </summary>
        internal static string SanCertificatesarenotsupportedbytheAzureWebAppPlugin {
            get {
                return ResourceManager.GetString("SanCertificatesarenotsupportedbytheAzureWebAppPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving certificate to {file}.
        /// </summary>
        internal static string Savingcertificatetofile {
            get {
                return ResourceManager.GetString("Savingcertificatetofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving issuer certificate to {file}.
        /// </summary>
        internal static string Savingissuercertificatetofile {
            get {
                return ResourceManager.GetString("Savingissuercertificatetofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving registration.
        /// </summary>
        internal static string Savingregistration {
            get {
                return ResourceManager.GetString("Savingregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving signer.
        /// </summary>
        internal static string Savingsigner {
            get {
                return ResourceManager.GetString("Savingsigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning IIS site bindings for hosts.
        /// </summary>
        internal static string ScanningIISsitebindingsforhosts {
            get {
                return ResourceManager.GetString("ScanningIISsitebindingsforhosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning IIS sites.
        /// </summary>
        internal static string ScanningIISsites {
            get {
                return ResourceManager.GetString("ScanningIISsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See {0} for more information..
        /// </summary>
        internal static string Seelinkformoreinformation {
            get {
                return ResourceManager.GetString("Seelinkformoreinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the host names for the certificate
        ///You can enter multiple IDs comma-separated e.g. 1,2,3.
        /// </summary>
        internal static string Selectthehostnamesforthecertificate {
            get {
                return ResourceManager.GetString("Selectthehostnamesforthecertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set private key exportable.
        /// </summary>
        internal static string Setprivatekeyexportable {
            get {
                return ResourceManager.GetString("Setprivatekeyexportable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Binding failed.
        /// </summary>
        internal static string SSLBindingfailed {
            get {
                return ResourceManager.GetString("SSLBindingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting answer.
        /// </summary>
        internal static string Submittinganswer {
            get {
                return ResourceManager.GetString("Submittinganswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ACME server was probably unable to reach {answerUri}.
        /// </summary>
        internal static string TheACMEserverwasprobablyunabletoreachanswerUri {
            get {
                return ResourceManager.GetString("TheACMEserverwasprobablyunabletoreachanswerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FTP Credentials are not set. Please specify them and try again..
        /// </summary>
        internal static string TheFTPCredentialsarenotset {
            get {
                return ResourceManager.GetString("TheFTPCredentialsarenotset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP binding is IP specific; the app can create it. However, if you have other HTTPS sites they will all get an invalid certificate error until you manually edit one of their HTTPS bindings..
        /// </summary>
        internal static string TheHTTPbindingisIPspecific {
            get {
                return ResourceManager.GetString("TheHTTPbindingisIPspecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebDAV credentials are not set. Please specify them and try again..
        /// </summary>
        internal static string TheWebDAVcredentialsarenotset {
            get {
                return ResourceManager.GetString("TheWebDAVcredentialsarenotset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find IIS site ID #{0}.
        /// </summary>
        internal static string UnabletofindIISsiteID {
            get {
                return ResourceManager.GetString("UnabletofindIISsiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set RSA Key Bits, Letting ACMESharp default key bits, Error: {@ex}.
        /// </summary>
        internal static string UnabletosetRSAKeyBits {
            get {
                return ResourceManager.GetString("UnabletosetRSAKeyBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating existing SSL binding.
        /// </summary>
        internal static string UpdatingexistingSSLbinding {
            get {
                return ResourceManager.GetString("UpdatingexistingSSLbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating registration.
        /// </summary>
        internal static string Updatingregistration {
            get {
                return ResourceManager.GetString("Updatingregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Status {StatusDescription}.
        /// </summary>
        internal static string UploadStatusDescription {
            get {
                return ResourceManager.GetString("UploadStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using SSL.
        /// </summary>
        internal static string UsingSSL {
            get {
                return ResourceManager.GetString("UsingSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for site to warm up....
        /// </summary>
        internal static string Waitingforsitetowarmup {
            get {
                return ResourceManager.GetString("Waitingforsitetowarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning creating SSL binding for {0}..
        /// </summary>
        internal static string WarningcreatingSSLbindingforhost {
            get {
                return ResourceManager.GetString("WarningcreatingSSLbindingforhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebDAV.
        /// </summary>
        internal static string WebDAV {
            get {
                return ResourceManager.GetString("WebDAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  W: Generate a certificate via WebDAV and install it manually..
        /// </summary>
        internal static string WebDAVMenuOption {
            get {
                return ResourceManager.GetString("WebDAVMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing challenge answer to {answerPath}.
        /// </summary>
        internal static string WritingchallengeanswertoanswerPath {
            get {
                return ResourceManager.GetString("WritingchallengeanswertoanswerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing web.config to add extensionless mime type to {webConfigPath}.
        /// </summary>
        internal static string WritingWebConfig {
            get {
                return ResourceManager.GetString("WritingWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find the certificate at {pfxFilename}.
        /// </summary>
        internal static string YoucanfindthecertificateatpfxFilename {
            get {
                return ResourceManager.GetString("YoucanfindthecertificateatpfxFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too many hosts for a San certificate. Let&apos;s Encrypt currently has a maximum of 100 alternative names per certificate..
        /// </summary>
        internal static string YouhavetoomanyhostsforaSancertificate {
            get {
                return ResourceManager.GetString("YouhavetoomanyhostsforaSancertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to edit the binding, turn off SNI, click OK, edit it again, enable SNI and click OK. That should fix the error..
        /// </summary>
        internal static string YouneedtoeditthebindingturnoffSNI {
            get {
                return ResourceManager.GetString("YouneedtoeditthebindingturnoffSNI", resourceCulture);
            }
        }
    }
}
