//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsEncrypt.ACME.Simple.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version = \"1.0\" encoding=\"UTF-8\"?>\r\n<configuration>\r\n\t<system.webServer>\r\n\t" +
            "\t<staticContent>\r\n\t\t\t<mimeMap fileExtension=\"*\" mimeType=\"text/json\" />\r\n\t\t</sta" +
            "ticContent>\r\n\t</system.webServer>\r\n</configuration>")]
        public string IISWebConfig {
            get {
                return ((string)(this["IISWebConfig"]));
            }
        }
    }
}
